api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

app_admin:
    resource: '@AppBundle/Resources/config/routing_admin.yml'
    prefix: /admin
