parameters:
    app.current_user.class: Biz\User\CurrentUser
    mobile.secret: MobileToken

services:
    app.user_provider:
        class: Biz\User\UserProvider
        arguments: ['@service_container']

    app.simple_form_authenticator:
        class: AppBundle\GuardAuthenticator\FormAuthenticator
        arguments: ["@security.password_encoder", "@service_container"]

    app.mobile_code_authenticator:
        class: AppBundle\GuardAuthenticator\MobileCodeGuardAuthenticator
        arguments: ["@service_container", "%mobile.secret%"]

security:
    providers:
        user_provider:
            id: app.user_provider

    encoders:
        "%app.current_user.class%":
            algorithm: sha256
            encode_as_base64: true
            iterations: 5000

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        disabled:
            pattern: ^/(anon|callback)/
            security: false

        main:
            anonymous: ~
            remember_me:
                secret: '%secret%'
                lifetime: 60
            provider: user_provider
            guard:
                authenticators:
                    - app.mobile_code_authenticator
            simple_form:
                authenticator: app.simple_form_authenticator
                login_path: login
                check_path: login
#            form_login:
#                login_path: login
#                check_path: login
#                failure_handler: topxia.authentication.failure_handler
#                success_handler: topxia.authentication.success_handler
#
#        secured_area:
#            pattern: ^/admin/
#            provider: user_provider
#            guard:
#                authenticators:
#                    - app.admin_authenticator

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/crontab, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }